### PR TITLE
Allow multiple metrics selection

### PR DESCRIPTION
**Pull request by jotak**
(using ctrl key for multiple selection)
Displays multiline charts in case of multiple selected metrics

Also allow configuring the number of buckets

### CODE REVIEW

**Comment by jotak** [comment]
PR dependency: https://github.com/hawkular/hawkular-charts/pull/179

**Comment by jotak** [comment]
Related ticket: https://github.com/hawkular/hawkular-ui/issues/9

**Comment by lucasponce** [comment]
\o/

**Comment by jmazzitelli** [comment]
It's ABOUT TIME!

LOL

**Comment by jotak** [comment]
I was waiting for your review! :D

**Pull request closed without merging**
