### PR TITLE
Display availability charts

### PR DESCRIPTION
**Pull request by jotak**
Also added authHeader to chart components
Also renamed title to Hawkular Metrics, not just Hawkular

### CODE REVIEW

**Comment by jotak** [comment]
http://imgur.com/a/O5X8C

**Comment by mtho11** [comment]
Looks like this requires: https://github.com/hawkular/hawkular-charts/pull/177

**Comment by jotak** [comment]
indeed

**Review by mtho11 — APPROVED** [review]
Good to see availability in here. It is quite important. Nice!

**Comment by jotak** [comment]
Thanks @mtho11 ; by the way, have you ever thought of a way to represent string metrics?

**Comment by mtho11** [comment]
@jotak Hmm, maybe a builder pattern?

**Pull request merged**
